flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- generator-0.5.5
- cryptohash-sha256-0.11.100.1
- aeson-pretty-0.8.2
resolver: lts-7.13
pvp-bounds: both
build:
  library-profiling: true
  executable-profiling: true
